import {
  noop,
  reject as _reject
} from '../-internal';

/**
  `Promise.reject` returns a promise rejected with the passed `reason`.
  It is shorthand for the following:

  ```javascript
<<<<<<< HEAD
  var promise = new Promise(function(resolve, reject){
=======
  let promise = new Promise(function(resolve, reject){
>>>>>>> ec8051100d234fe9175dcd73a88d8192aa153d52
    reject(new Error('WHOOPS'));
  });

  promise.then(function(value){
    // Code here doesn't run because the promise is rejected!
  }, function(reason){
    // reason.message === 'WHOOPS'
  });
  ```

  Instead of writing the above, your code now simply becomes the following:

  ```javascript
<<<<<<< HEAD
  var promise = Promise.reject(new Error('WHOOPS'));
=======
  let promise = Promise.reject(new Error('WHOOPS'));
>>>>>>> ec8051100d234fe9175dcd73a88d8192aa153d52

  promise.then(function(value){
    // Code here doesn't run because the promise is rejected!
  }, function(reason){
    // reason.message === 'WHOOPS'
  });
  ```

  @method reject
  @static
  @param {Any} reason value that the returned promise will be rejected with.
  Useful for tooling.
  @return {Promise} a promise rejected with the given `reason`.
*/
export default function reject(reason) {
  /*jshint validthis:true */
<<<<<<< HEAD
  var Constructor = this;
  var promise = new Constructor(noop);
=======
  let Constructor = this;
  let promise = new Constructor(noop);
>>>>>>> ec8051100d234fe9175dcd73a88d8192aa153d52
  _reject(promise, reason);
  return promise;
}
